.PHONY: init update

DIR:=$(shell basename $(PWD))

init:
	git fetch
	git submodule init
	git submodule update --recursive
	git submodule foreach "git fetch && git submodule init"
	git submodule update --recursive
